### ISSUE TITLE
Slurm Dashboard Link /operations/monitoring.html

### ISSUE THREAD

**Issue by flakrat** [omnivector-solutions/osd-documentation#84]
The link to the Slurm Grafana dashboard has apparently changed
* From: https://grafana.com/dashboards/4323
* To: https://grafana.com/grafana/dashboards/4323-slurm-dashboard/

**Comment by jaimesouza** [comment]
Thank you @flakrat! We will fix that in the documentation soon.

**Comment by jaimesouza** [comment]
Fixed!
